name: panther
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.2.2=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cudatoolkit=11.4.1=h8ab8bb3_9
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - faiss-gpu=1.7.4=py3.10_hc0239a3_0_cuda11.4
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libfaiss=1.7.4=h13c3c6d_0_cuda11.4
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py310h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.10.14=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.1.0
    - appdirs==1.4.4
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.1
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - ecos==2.0.13
    - einops==0.7.0
    - filelock==3.13.4
    - fonttools==4.51.0
    - fsspec==2024.3.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - grpcio==1.62.2
    - h5py==3.11.0
    - huggingface-hub==0.22.2
    - idna==3.7
    - intel-openmp==2024.1.0
    - jinja2==3.1.3
    - joblib==1.4.0
    - kiwisolver==1.4.5
    - markdown==3.6
    - markupsafe==2.1.5
    - matplotlib==3.8.4
    - mkl==2024.1.0
    - mpmath==1.3.0
    - networkx==3.3
    - numexpr==2.10.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - nystrom-attention==0.0.12
    - osqp==0.6.5
    - pandas==2.2.2
    - pillow==10.3.0
    - protobuf==4.25.3
    - pyparsing==3.1.2
    - pytz==2024.1
    - pyyaml==6.0.1
    - qdldl==0.1.7.post2
    - regex==2024.4.16
    - requests==2.31.0
    - safetensors==0.4.3
    - scikit-learn==1.3.2
    - scikit-survival==0.22.2
    - scipy==1.11.4
    - seaborn==0.13.2
    - sentry-sdk==1.45.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - sympy==1.12
    - tbb==2021.12.0
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.4.0
    - tokenizers==0.19.1
    - torch==2.2.2
    - torchvision==0.17.2
    - tqdm==4.66.2
    - transformers==4.40.0
    - triton==2.2.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - wandb==0.16.6
    - werkzeug==3.0.2
prefix: /home/andrew/anaconda3/envs/panther
